"""Configuration and schema definitions."""

from aquacal.config.schema import (
    Vec2,
    Vec3,
    Mat3,
    BoardConfig,
    CameraIntrinsics,
    CameraExtrinsics,
    CameraCalibration,
    InterfaceParams,
    CalibrationResult,
    DiagnosticsData,
    CalibrationMetadata,
    CalibrationConfig,
    BoardPose,
    Detection,
    FrameDetections,
    DetectionResult,
    CalibrationError,
    InsufficientDataError,
    ConvergenceError,
    ConnectivityError,
)

__all__ = [
    "Vec2",
    "Vec3",
    "Mat3",
    "BoardConfig",
    "CameraIntrinsics",
    "CameraExtrinsics",
    "CameraCalibration",
    "InterfaceParams",
    "CalibrationResult",
    "DiagnosticsData",
    "CalibrationMetadata",
    "CalibrationConfig",
    "BoardPose",
    "Detection",
    "FrameDetections",
    "DetectionResult",
    "CalibrationError",
    "InsufficientDataError",
    "ConvergenceError",
    "ConnectivityError",
]
